### ISSUE TITLE
Consider removing min 500 chars for description/[lang]/longDescription

### ISSUE THREAD

**Issue by johanlinaker** [publiccodeyml/publiccode.yml#129]
Currently, there is a minimum requirement of 500 characters for the key description/[lang]/longDescription. 

I propose removing this lower bar, or changing it to 150, which is the upper bar for the short description.

For example, if a 400 char description is considered enough, why force the author to put in 100 char extra?

**Comment by giosce** [comment]
I'm very much in favor!
I'd add that these setting should be in a config file, it doesn't make sense to fork the project just to change which fields are mandatory or their minimum lenght.

**Comment by bfabio** [comment]
@johanlinaker I agree as well +1

I can open a PR with the proposal with this, unless you prefer to do it yourself

**Comment by johanlinaker** [comment]
Please go ahead! :)
