### ISSUE TITLE
publiccode.minimal.yml should be updated with an example using up to date standard (0.4.0)

### ISSUE THREAD

**Issue by evilaliv3** [publiccodeyml/publiccode.yml#194]
https://github.com/publiccodeyml/publiccode.yml/blob/68b56afa9522e70bd8132ac5362535997f0b03c5/docs/en/example/publiccode.minimal.yml#L1

**Comment by bfabio** [comment]
See [195#issuecomment-2309637749](https://github.com/publiccodeyml/publiccode.yml/issues/195#issuecomment-2309637749)
