### ISSUE TITLE
Consider allowing longer features

### ISSUE THREAD

**Issue by alranel** [publiccodeyml/publiccode.yml#58]
As of now, each feature under `description/[lang]/features` shall not exceed 100 characters. This is a bit too short, as longer sentences might be needed, especially when mentioning laws etc. 200 or 250 might be good values.

**Comment by bfabio** [comment]
We could just remove the limit in the Standard and have each presentation level (ie. websites / catalogs / search engines) decide if and how to truncate them.

Drafting a proposal
