### ISSUE TITLE
Consider removing genericName

### ISSUE THREAD

**Issue by alranel** [publiccodeyml/publiccode.yml#59]
As of now, `genericName` is mandatory and limited to 35 characters.

However, field experience is showing that this field always contains information that is already carried by `shortDescription`, `softwareType` and `categories`. We should consider removing `genericName` if no good reason for it arises.

**Comment by bfabio** [comment]
Posted to the forum as https://publiccode.discourse.group/t/consider-removing-genericname-issue-59/65
