### ISSUE TITLE
Consider relaxing the format of inputTypes and outputTypes

### ISSUE THREAD

**Issue by alranel** [publiccodeyml/publiccode.yml#63]
As of now, inputTypes and outputTypes are restricted to MIME types. This is proving to be a bit too restrictive, as some file types/extensions do not have a MIME type. We should consider relaxing this syntactic requirement, maybe turning it into a recommendation (so that editors can display a tentative combobox instead of a comprehensive dropdown).

**Comment by bfabio** [comment]
I think we'd be better off deprecating them and eventually removing them (#147)

**Comment by bfabio** [comment]
Closing, as they are now deprecated with #147
