### ISSUE TITLE
"This repository is structured in order to be compatible with the Docs Italia platform."

### ISSUE THREAD

**Issue by AndreaTironi1** [publiccodeyml/publiccode.yml#65]
Ciao.

Ho provato a fare il mio primo "publiccode.yml".
Ho letto il readme e nella sezione Documentation farei un'aggiunta e/o una modifica.
Forse sono io che non mastico molto la materia, ma non avevo capito che

"This repository is structured in order to be compatible with the Docs Italia platform."
voleva dire: vai al link e leggiti le istruzioni

Così mi sono fatto un mio publiccode.yml copiando quelli di 18app, per poi capire che
in docs italia platform c'era l'editor.

Potrebbe essere interessante mettere nella documentazione dopo

"This repository is structured in order to be compatible with the Docs Italia platform."
Una riga che dica (scusate l'inglese, ci provo)
"If you want a fast track to create your publiccode.yml go [here](link all'editor)"

Grazie mille!
E' stato divertente provare a rendere codice pubblico per il nostro Paese e la PA!
Spero che il mio codice sia indexato correttamente e di non aver fatto qualche errore, nonchè sia utile ad altri!

Andrea

**Comment by libremente** [comment]
Buongiorno Andrea e grazie per la segnalazione. 
Questo repository è stato strutturato per contenere sorgenti che sono compilati e resi accessibili all'interno della piattaforma Docs Italia che ben si presta alla consultazione di materiale testuale.
Per questo motivo è presente un link alla piattaforma che consideriamo l'entry point per la documentazione relativa a questo formato e che contiene anche le indicazioni relative agli strumenti di supporto (ad es., l'editor). 
Inserire il collegamento all'editor direttamente da questo `README` potrebbe essere d'aiuto ma non vorrei che lo standard non venisse consultato e quindi devo capire come presentare questa possibilità.
Ti tengo aggiornato, grazie! @AndreaTironi1

**Comment by AndreaTironi1** [comment]
Grazie a te per la risposta :)

Posso chidere sempre a te per capire perchè il mio codice non è stato
indicizzato su developers
nonostante abbiamo messo il publiccode.yml? Probabilmente avrò sbagliato
qualcosa ma non saprei cosa.

Grazie.

Andrea

Il giorno mar 13 ago 2019 alle ore 11:15 libremente <
notifications@github.com> ha scritto:

**Comment by libremente** [comment]
@AndreaTironi1 Certamente. Mi puoi indicare il repository contenente il `publiccode.yml`? La procedura di [onboarding](https://onboarding.developers.italia.it/) è stata correttamente completata?

**Comment by AndreaTironi1** [comment]
CIao.

Il repository è:
https://github.com/AndreaTironi1/io

L'onboarding non l'avevo fatto, non sapevo che dovevo iscrivermi: avevo
capito che veniva indicizzato da un crawler e infatti
mi domandavo: ma non parserà mica tutto guthib :) Ecco la risposta,
l'onboarding :)

Ho provato a compilarlo ma mi dice che:
https://github.com/AndreaTironi1/io -
"Indirizzo URL non presente nella whitelist: ricompila il form  "

Attendo gentilmente tue, grazie mille.

Andrea

Il giorno mar 13 ago 2019 alle ore 11:26 libremente <
notifications@github.com> ha scritto:

**Comment by libremente** [comment]
Ok, siccome siamo OT in questa issue, sposterei la conversazione su Slack di Developers Italia, canale #reuse. Ti contatto io in quella sede. Grazie!

**Comment by bfabio** [comment]
Closing old issue, feel free to reopen it if you think there's something still pending.
