### ISSUE TITLE
Do not limit contact's pointers to email

### ISSUE THREAD

**Issue by mfortini** [publiccodeyml/publiccode.yml#90]
A software could have:

- a website
- one or more social pages
- a Forum Italia topic
- ...

Which could be helpful to learn more about it or ask questions.

Expand the Contact https://docs.italia.it/italia/developers-italia/publiccodeyml/it/master/schema.core.html#contatto
definition to allow for URLs and not just emails.

**Comment by ruphy** [comment]
https://publiccode.discourse.group/t/do-not-limit-contacts-pointers-to-email/59
