### ISSUE TITLE
Clarification on intendedAudience/countries key usage when the software has a broad worldwide target audience

### ISSUE THREAD

**Issue by evilaliv3** [publiccodeyml/publiccode.yml#95]
While working on the [Globaleaks](https://github.com/globaleaks/GlobaLeaks/blob/main/publiccode.yml) publication we are experiencing difficulties giving a value to the key ```intendedAudience```.

Similarly to a Content Management System (CMS), GlobaLeaks has a broad target audience so that  the current ```intendedAudience``` seems to require to list an unlimited set of country codes with significant inefficiency.

I suggest this key could be extended / documented clarifying how this condition should be handled.

**Comment by ruphy** [comment]
@evilaliv3 could you please move this to https://publiccode.discourse.group/ ?
I am sunsetting the issues here. Thanks!
