### ISSUE TITLE
Add "Whistleblowing" to the software categories list

### ISSUE THREAD

**Issue by evilaliv3** [publiccodeyml/publiccode.yml#96]
Whistleblowing software is a category of software that currently does not fit in any of the currently defined [software categories list](https://github.com/publiccodeyml/publiccode.yml/blob/master/docs/it/categories-list.rst) and that is defined by many existing and upcoming regulations (e.g. 190/2012, 179/2017, EU Regulation 2016/679) that determine specific software capabilities.

This ticket is to propose the addition of a specific software category "Whistleblowing".

Here are examples of two softwares that would fit in this category: 
- https://developers.italia.it/it/software/globaleaks-globaleaks-f22648.html
- https://developers.italia.it/it/software/c_l736-comune_venezia-whistleblowing

**Comment by libremente** [comment]
Thanks a lot @evilaliv3 also for the PR!
This looks OK to me, `whisteblowing` should be a standalone category. 
WDYT @ruphy @sebbalex @bfabio?

**Comment by ruphy** [comment]
reposted this on the forum: https://publiccode.discourse.group/t/add-whistleblowing-to-the-software-categories-list-repost-issue-96/57

**Comment by ruphy** [comment]
@evilaliv3 if you can register on the forum, I can change the ownership of the issue too :-)

**Comment by evilaliv3** [comment]
I just received the notification by github that this issus has been opened again! this is c00l.

Is there anything that i could do to support thi this work to move forward @ruphy ?

Thank you!

**Comment by bfabio** [comment]
Hey @evilaliv3, we're setting up a new governance and an international working group that should be [able to vote on proposals](https://github.com/publiccodeyml/publiccode.yml/blob/main/governance/procedure-proposing-changes-and-voting.md) pretty soon!

**Comment by evilaliv3** [comment]
Rebased! thank you @bfabio !
