### ISSUE TITLE
User landingURL variable to create a link to the project site

### ISSUE THREAD

**Issue by evilaliv3** [publiccodeyml/publiccode.yml#99]
While working on the publication of GlobaLeaks  i've noticed that the variable ``landingURL`` (https://github.com/globaleaks/GlobaLeaks/blob/main/publiccode.yml#L5) apprears not used anywhere on the [profile of the software](https://developers.italia.it/it/software/globaleaks-globaleaks-f22648.html).

This ticket is to propose to use the value of the landingURL variable in order to create a link "Site" on the right sidebar to be shown over the link "Documentation

![Screenshot_2021-06-29 GlobaLeaks - Developers Italia](https://user-images.githubusercontent.com/217034/123836849-7291f300-d90a-11eb-9f16-199ea7838b7c.png)

**Comment by ruphy** [comment]
@evilaliv3 this issue is related to the frontend here: https://github.com/italia/developers.italia.it
I unfortunately cannot transfer the issue as it's of a different organization. would you mind transfering it yourself?

Thanks!! :pray:

**Comment by evilaliv3** [comment]
You are welcome @ruphy , thank you!

Let me re-create it right away!
